export enum ESkills {
	HTML5 = "HTML5",
	CSS = "CSS",
	JAVASCRIPT = "JAVASCRIPT",
	TYPESCRIPT = "TYPESCRIPT",
	REACT = "REACT",
	NEXT = "NEXT",
	REACTNATIVE = "REACTNATIVE",
	VUE = "VUE",
	SASS = "SASS",
	TAILWIND = "TAILWIND",
}
